/*
 * I2C.cpp
 *
 * Created: 16.06.2019 16:56:37
 *  Author: JackFrost
 */ 

#include "sam.h"
#include "I2C.h"

void init_i2c()
{
	MCLK->APBCMASK.bit.SERCOM2_ = 1;
	GCLK->PCHCTRL[SERCOM2_GCLK_ID_CORE].bit.GEN = 0;
	GCLK->PCHCTRL[SERCOM2_GCLK_ID_CORE].bit.CHEN = 1;
	while(GCLK->PCHCTRL[SERCOM2_GCLK_ID_CORE].bit.CHEN != 1);
	SERCOM2->I2CM.CTRLA.bit.ENABLE = 0;
	SERCOM2->I2CM.SYNCBUSY.bit.ENABLE = 1;
	while (SERCOM2->I2CM.SYNCBUSY.bit.ENABLE);
	SERCOM2->I2CM.CTRLA.bit.MODE = 0x05; //Mastermode
	SERCOM2->I2CM.BAUD.bit.BAUD = 5; // 400 khz bei 48 MHz fclock/fi2x*2 -1
	
	PORT->Group[0].PMUX[6].bit.PMUXE = MUX_PA12C_SERCOM2_PAD0;
	PORT->Group[0].PMUX[6].bit.PMUXO = MUX_PA13C_SERCOM2_PAD1;
	PORT->Group[0].PINCFG[12].bit.PMUXEN = 1;
	PORT->Group[0].PINCFG[13].bit.PMUXEN = 1;
	SERCOM2->I2CM.CTRLA.bit.ENABLE = 1;
	SERCOM2->I2CM.SYNCBUSY.bit.ENABLE = 1;
	while (SERCOM2->I2CM.SYNCBUSY.bit.ENABLE);
	SERCOM2->I2CM.STATUS.bit.BUSSTATE = 0x01; // IDLE bus
	//PINMUX_PA12C_SERCOM2_PAD0
	//PINMUX_PA13C_SERCOM2_PAD1
}